# Generated by Django 5.2.9 on 2026-03-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grid_size', models.IntegerField(default=4)),
                ('grid', models.JSONField(blank=True, null=True)),
                ('dictionary_ref', models.CharField(default='English', max_length=50)),
                ('solution_set', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='game_engine.game')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('words_found', models.JSONField(default=list)),
                ('words_not_found', models.JSONField(default=list)),
                ('time_elapsed', models.IntegerField(help_text='Time in seconds')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game_engine.leaderboard')),
            ],
        ),
    ]
